- name: Deploy an Engaging Website
  hosts: all
  become: yes  # Use this to run tasks as sudo
  tasks:
    - name: Install Apache Web Server (httpd)
      package:
        name: "{{ ansible_facts.packages['httpd'] | default('apache2') }}"
        state: present

    - name: Copy the index.html file to the web server
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data  # Use the correct user for your web server
        group: www-data  # Use the correct group for your web server
        mode: '0644'

    - name: Ensure Apache is started and enabled
      service:
        name: "{{ ansible_facts.packages['httpd'] | default('apache2') }}"
        state: started
        enabled: yes
