---
- name: Deploy an Engaging Website
  hosts: all
  become: yes  # Use this to run tasks as sudo
  vars:
    # Define the web server user and group as variables
    web_server_user: "www-data"  # Default for Ubuntu/Debian, can change to "httpd" for CentOS/RHEL
    web_server_group: "www-data"  # Change to "httpd" if needed

  tasks:
    - name: Install Apache Web Server (httpd)
      package:
        name: "{{ ansible_facts.packages['httpd'] | default('apache2') }}"
        state: present

    - name: Copy the index.html file to the web server
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: "{{ web_server_user }}"  # Use the variable for the user
        group: "{{ web_server_group }}"  # Use the variable for the group
        mode: '0644'

    - name: Ensure Apache is started and enabled
      service:
        name: "{{ ansible_facts.packages['httpd'] | default('apache2') }}"
        state: started
        enabled: yes
